# Generated by Django 5.1.5 on 2025-07-13 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutApp', '0002_customuser_otp_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('otp', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.IntegerField(max_length=11, unique=True)),
                ('license_number', models.CharField(max_length=15)),
                ('field_specialisation', models.CharField(blank=True, max_length=10)),
                ('health_institution', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livesessions', to='workoutApp.consultants')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
